Repository CondensateCrew/Condensate, pull requests merged in 2020-02, with the labels that each got.

#15 Sass Setup
  src/css/index.scss
  src/css/reset.scss
  src/css/variables.scss
  src/index.scss
  src/index.tsx
Labels: frontend, phase2

#17 Login form
  package-lock.json
  package.json
  src/Components/App/App.test.tsx
  src/Components/App/App.tsx
  src/Components/App/__snapshots__/App.test.tsx.snap
  src/Components/LoginForm/LoginForm.test.tsx
  src/Components/LoginForm/LoginForm.tsx
  src/Components/LoginForm/__snapshots__/LoginForm.test.tsx.snap
  src/_utils/index.test.ts
  src/_utils/index.ts
  src/interfaces.ts
  src/redux/actions/index.ts
  src/redux/reducers/index.ts
  src/redux/reducers/userReducer.test.ts
  src/redux/reducers/userReducer.ts
  tsconfig.json
Labels: frontend, phase2

#28 Add and test Reducers
  src/index.tsx
  src/interfaces.ts
  src/redux/actions/actions.test.ts
  src/redux/actions/index.ts
  src/redux/reducers/actions/actions.test.ts
  src/redux/reducers/actions/actions.ts
  src/redux/reducers/allBrainstorms/allBrainstorms.test.ts
  src/redux/reducers/allBrainstorms/allBrainstorms.ts
  src/redux/reducers/categories/categories.test.ts
  src/redux/reducers/categories/categories.ts
  src/redux/reducers/chosenWords/chosenWords.test.ts
  src/redux/reducers/chosenWords/chosenWords.ts
  src/redux/reducers/currentBrainstorm/currentBrainstorm.test.ts
  src/redux/reducers/currentBrainstorm/currentBrainstorm.ts
  src/redux/reducers/filter/filter.test.ts
  src/redux/reducers/filter/filter.ts
  src/redux/reducers/index.ts
  src/redux/reducers/insights/insights.test.ts
  src/redux/reducers/insights/insights.ts
  src/redux/reducers/instructionsEnded/instructionsEnded.test.ts
  src/redux/reducers/instructionsEnded/instructionsEnded.ts
  src/redux/reducers/query/query.test.ts
  src/redux/reducers/query/query.ts
  src/redux/reducers/questionTemplates/questionTemplates.test.ts
  src/redux/reducers/questionTemplates/questionTemplates.ts
  src/redux/reducers/randomWordCollections/randomWordCollection.test.ts
  src/redux/reducers/randomWordCollections/randomWordCollections.ts
  src/redux/reducers/secretSauce/secretSauce.test.ts
  src/redux/reducers/secretSauce/secretSauce.ts
  src/redux/reducers/timeEnded/timeEnded.test.ts
  src/redux/reducers/timeEnded/timeEnded.ts
  src/redux/reducers/user/user.test.ts
  src/redux/reducers/user/user.ts
Labels: frontend, phase2

#30 Brainstorm board
  src/Components/BrainstormCard/BrainstormCard.scss
  src/Components/BrainstormCard/BrainstormCard.test.tsx
  src/Components/BrainstormCard/BrainstormCard.tsx
  src/Components/BrainstormCard/__snapshots__/BrainstormCard.test.tsx.snap
  src/Components/CategoriesFilter/CategoriesFilter.tsx
  src/Components/SearchBar/SearchBar.tsx
  src/Containers/BrainstormContainer/BrainstormContainer.scss
  src/Containers/BrainstormContainer/BrainstormContainer.test.tsx
  src/Containers/BrainstormContainer/BrainstormContainer.tsx
  src/Containers/BrainstormContainer/__snapshots__/BrainstormContainer.test.tsx.snap
  src/Containers/BrainstormContainer/mockData.ts
  src/Containers/CategoriesFilter/CategoriesFilter.scss
  src/Containers/CategoriesFilter/CategoriesFilter.test.tsx
  src/Containers/CategoriesFilter/CategoriesFilter.tsx
  src/Containers/CategoriesFilter/__snapshots__/CategoriesFilter.test.tsx.snap
  src/Containers/Dashboard/Dashboard.scss
  src/Containers/Dashboard/Dashboard.test.tsx
  src/Containers/Dashboard/Dashboard.tsx
  src/Containers/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/Containers/MenuBlock/MenuBlock.scss
  src/Containers/MenuBlock/MenuBlock.test.tsx
  src/Containers/MenuBlock/MenuBlock.tsx
  src/Containers/MenuBlock/__snapshots__/MenuBlock.test.tsx.snap
  src/Containers/SearchBar/SearchBar.scss
  src/Containers/SearchBar/SearchBar.test.tsx
  src/Containers/SearchBar/SearchBar.tsx
  src/Containers/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/assets/close.svg
  src/assets/delete.svg
  src/assets/down.svg
  src/assets/idea.svg
  src/assets/menu-dot.svg
  src/assets/search.svg
  src/css/index.scss
  src/css/variables.scss
  src/interfaces.ts
  src/redux/actions/actions.test.ts
  src/redux/actions/index.ts
  src/redux/reducers/allBrainstorms/allBrainstorms.test.ts
  src/redux/reducers/allBrainstorms/allBrainstorms.ts
Labels: frontend, phase2

#38 Add Header and Timer components
  src/Components/Header/Header.scss
  src/Components/Header/Header.test.tsx
  src/Components/Header/Header.tsx
  src/Components/Header/__snapshots__/Header.test.tsx.snap
  src/Components/Timer/Timer.scss
  src/Components/Timer/Timer.test.tsx
  src/Components/Timer/Timer.tsx
  src/Components/Timer/__snapshots__/Timer.test.tsx.snap
Labels: frontend, phase2

#41 Add Round one game
  src/Components/App/App.tsx
  src/Components/App/__snapshots__/App.test.tsx.snap
  src/Containers/ChosenWordTrain/ChosenWordTrain.scss
  src/Containers/ChosenWordTrain/ChosenWordTrain.test.tsx
  src/Containers/ChosenWordTrain/ChosenWordTrain.tsx
  src/Containers/ChosenWordTrain/__snapshots__/ChosenWordTrain.test.tsx.snap
  src/Containers/GameBoard/GameBoard.scss
  src/Containers/GameBoard/GameBoard.test.tsx
  src/Containers/GameBoard/GameBoard.tsx
  src/Containers/GameBoard/__snapshots__/GameBoard.test.tsx.snap
  src/Containers/GameBoard/mockData.ts
  src/Containers/Round1/Round1.tsx
  src/Containers/RoundOne/RoundOne.scss
  src/Containers/RoundOne/RoundOne.test.tsx
  src/Containers/RoundOne/RoundOne.tsx
  src/Containers/RoundOne/__snapshots__/RoundOne.test.tsx.snap
  src/assets/down.svg
  src/css/variables.scss
Labels: frontend, phase2

#40 Round two
  public/favicon.ico
  src/Components/App/App.tsx
  src/Components/App/__snapshots__/App.test.tsx.snap
  src/Components/GenerateInsights/GenerateInsights.scss
  src/Components/GenerateInsights/GenerateInsights.tsx
  src/Components/Insights/Insights.scss
  src/Components/Insights/Insights.tsx
  src/Components/Instruction/Instruction.scss
  src/Components/Instruction/Instruction.test.tsx
  src/Components/Instruction/Instruction.tsx
  src/Components/Instruction/__snapshots__/Instruction.test.tsx.snap
  src/Components/TemplateQuestion/TemplateQuestion.scss
  src/Components/TemplateQuestion/TemplateQuestion.test.tsx
  src/Components/TemplateQuestion/TemplateQuestion.tsx
  src/Components/TemplateQuestion/__snapshots__/TemplateQuestion.test.tsx.snap
  src/Containers/Insights/Insights.tsx
  src/Containers/Round2/Round2.tsx
  src/Containers/RoundOne/RoundOne.tsx
  src/Containers/RoundOne/__snapshots__/RoundOne.test.tsx.snap
  src/Containers/RoundTwo/RoundTwo.scss
  src/Containers/RoundTwo/RoundTwo.test.tsx
  src/Containers/RoundTwo/RoundTwo.tsx
  src/Containers/RoundTwo/__snapshots__/RoundTwo.test.tsx.snap
  src/_utils/index.ts
  src/assets/close.svg
  src/data/mockQuestionTemplate.ts
Labels: frontend, phase2

#50 Css ref add
  src/Components/DisplayInsights/DisplayInsights.scss
  src/Components/DisplayInsights/DisplayInsights.tsx
  src/Components/FinalIdeaField/FinalIdeaField.scss
  src/Components/FinalIdeaField/FinalIdeaField.tsx
  src/Components/GenerateInsights/GenerateInsights.scss
  src/Components/Instruction/Instruction.scss
  src/Components/Instruction/Instruction.test.tsx
  src/Components/Instruction/Instruction.tsx
  src/Components/Instruction/__snapshots__/Instruction.test.tsx.snap
  src/Components/SecretSauce/SecretSauce.scss
  src/Components/SecretSauce/SecretSauce.tsx
  src/Containers/IdeaEventHorizon/IdeaEventHorizon.scss
  src/Containers/Instructions/Instructions.scss
  src/Containers/Instructions/Instructions.tsx
  src/Containers/RoundTwo/RoundTwo.scss
  src/Containers/RoundTwo/RoundTwo.tsx
  src/Containers/RoundTwo/__snapshots__/RoundTwo.test.tsx.snap
  src/css/index.scss
Labels: css, frontend, phase3

#52 Tests refactoring
  src/Components/BrainstormCategory/BrainstormCategory.test.tsx
  src/Components/BrainstormCategory/__snapshots__/BrainstormCategory.test.tsx.snap
  src/Components/Button/Button.tsx
  src/Components/DisplayInsights/DisplayInsights.scss
  src/Components/DisplayInsights/DisplayInsights.test.tsx
  src/Components/DisplayInsights/DisplayInsights.tsx
  src/Components/DisplayInsights/__snapshots__/DisplayInsights.test.tsx.snap
  src/Components/FinalIdeaField/FinalIdeaField.scss
  src/Components/FinalIdeaField/FinalIdeaField.test.tsx
  src/Components/FinalIdeaField/FinalIdeaField.tsx
  src/Components/FinalIdeaField/__snapshots__/FinalIdeaField.test.tsx.snap
  src/Components/GenerateInsights/GenerateInsights.scss
  src/Components/GenerateInsights/GenerateInsights.test.tsx
  src/Components/GenerateInsights/GenerateInsights.tsx
  src/Components/GenerateInsights/__snapshots__/GenerateInsights.test.tsx.snap
  src/Components/IdeaQuestion/IdeaQuestion.test.tsx
  src/Components/IdeaQuestion/__snapshots__/IdeaQuestion.test.tsx.snap
  src/Components/InputElement/InputElement.test.tsx
  src/Components/InputElement/__snapshots__/InputElement.test.tsx.snap
  src/Components/Insights/Insights.test.tsx
  src/Components/Insights/__snapshots__/Insights.test.tsx.snap
  src/Components/Instruction/Instruction.scss
  src/Components/Instruction/Instruction.test.tsx
  src/Components/Instruction/Instruction.tsx
  src/Components/Instruction/__snapshots__/Instruction.test.tsx.snap
  src/Components/SecretSauce/SecretSauce.scss
  src/Components/SecretSauce/SecretSauce.test.tsx
  src/Components/SecretSauce/SecretSauce.tsx
  src/Components/SecretSauce/__snapshots__/SecretSauce.test.tsx.snap
  src/Components/UserProfile/UserProfile.test.tsx
  src/Components/UserProfile/__snapshots__/UserProfile.test.tsx.snap
  src/Containers/IdeaEventHorizon/IdeaEventHorizon.scss
  src/Containers/Instructions/Instructions.scss
  src/Containers/Instructions/Instructions.tsx
  src/Containers/RoundTwo/RoundTwo.scss
  src/Containers/RoundTwo/RoundTwo.tsx
  src/Containers/RoundTwo/__snapshots__/RoundTwo.test.tsx.snap
  src/css/index.scss
Labels: frontend, phase3
